import './globals.css'
import Navbar from '@/components/navigation/Navbar'
import BackToTopButton from '@/components/BackToTop'

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className="bg-light-primary">
                <Navbar />
                <div className="max-w-screen-3xl mx-auto">
                    {children}
                </div>
                <BackToTopButton />
            </body>
        </html>
    )
}